# POPULARITY ANALYSIS
The objective of this notebook is to investigate whether audience popularity is associated with box office success. This analysis examines the relationship between IMDb ratings, audience vote counts, and box office revenue to determine whether movies receiving higher audience engagement also achieve greater financial performance.


# Research Questions

- Does a movie's popularity score correlate with its financial success?
- Does the number of audience votes correlate with box office revenue?

In [8]:
import sqlite3
import pandas as pd

In [9]:
database = r"C:\Users\bongo\OneDrive\Desktop\GitHub\Movie Analysis\Database\movie_industry.db"

connection = sqlite3.connect(database)

print("Connected successfully.")

Connected successfully.

## HIGHEST RATED MOVIES

In [10]:
# HIGHEST RATED MOVIES

query = """
SELECT
    name,
    score,
    gross
FROM movies
WHERE score IS NOT NULL
ORDER BY score DESC
LIMIT 20;
"""

highest_scores = pd.read_sql(query, connection)

highest_scores

                                                 name  score         gross
0                            The Shawshank Redemption    9.3  2.881729e+07
1                                     The Dark Knight    9.0  1.005974e+09
2                                    Schindler's List    8.9  3.221612e+08
3                                        Pulp Fiction    8.9  2.139288e+08
4       The Lord of the Rings: The Return of the King    8.9  1.146031e+09
5                                        Forrest Gump    8.8  6.782261e+08
6                                          Fight Club    8.8  1.012097e+08
7   The Lord of the Rings: The Fellowship of the Ring    8.8  8.976901e+08
8                                           Inception    8.8  8.368370e+08
9      Star Wars: Episode V - The Empire Strikes Back    8.7  5.383751e+08
10                                         Goodfellas    8.7  4.696328e+07
11                                         The Matrix    8.7  4.663648e+08
12              The Lord of the Rings: The Two Towers    8.7  9.474951e+08
13                           The Silence of the Lambs    8.6  2.727429e+08
14                                              Se7en    8.6  3.273336e+08
15                                  Life Is Beautiful    8.6  2.300988e+08
16                                Saving Private Ryan    8.6  4.823496e+08
17                                     The Green Mile    8.6  2.868014e+08
18                                      Spirited Away    8.6  3.554752e+08
19                                        City of God    8.6  3.068079e+07

## MOST VOTED MOVIES

In [11]:
# MOST VOTED MOVIES

query = """
SELECT
    name,
    votes,
    gross
FROM movies
WHERE votes IS NOT NULL
ORDER BY votes DESC
LIMIT 20;
"""

most_voted = pd.read_sql(query, connection)

most_voted

                                                 name      votes         gross
0                            The Shawshank Redemption  2400000.0  2.881729e+07
1                                     The Dark Knight  2400000.0  1.005974e+09
2                                           Inception  2100000.0  8.368370e+08
3                                        Pulp Fiction  1900000.0  2.139288e+08
4                                        Forrest Gump  1900000.0  6.782261e+08
5                                          Fight Club  1900000.0  1.012097e+08
6                                          The Matrix  1700000.0  4.663648e+08
7   The Lord of the Rings: The Fellowship of the Ring  1700000.0  8.976901e+08
8       The Lord of the Rings: The Return of the King  1700000.0  1.146031e+09
9                               The Dark Knight Rises  1600000.0  1.081143e+09
10                                       Interstellar  1600000.0  7.017292e+08
11                                              Se7en  1500000.0  3.273336e+08
12              The Lord of the Rings: The Two Towers  1500000.0  9.474951e+08
13                                          Gladiator  1400000.0  4.653808e+08
14                                   Django Unchained  1400000.0  4.260744e+08
15                           The Silence of the Lambs  1300000.0  2.727429e+08
16                                Saving Private Ryan  1300000.0  4.823496e+08
17                                      Batman Begins  1300000.0  3.736619e+08
18                               Inglourious Basterds  1300000.0  3.214577e+08
19                                       The Avengers  1300000.0  1.518816e+09

## HIGHEST REVENUE MOVIES WITH HIGH SCORES

In [12]:
# HIGHEST REVENUE MOVIES WITH HIGH SCORES

query = """
SELECT
    name,
    score,
    gross
FROM movies
WHERE score >= 8.0
ORDER BY gross DESC
LIMIT 20;
"""

high_score_revenue = pd.read_sql(query, connection)

high_score_revenue

                                                 name  score         gross
0                                   Avengers: Endgame    8.4  2.797501e+09
1                              Avengers: Infinity War    8.4  2.048360e+09
2                                        The Avengers    8.0  1.518816e+09
3        Harry Potter and the Deathly Hallows: Part 2    8.1  1.342322e+09
4       The Lord of the Rings: The Return of the King    8.9  1.146031e+09
5                                       The Lion King    8.5  1.083721e+09
6                               The Dark Knight Rises    8.4  1.081143e+09
7                                               Joker    8.4  1.074427e+09
8                                         Toy Story 3    8.2  1.066971e+09
9                                       Jurassic Park    8.1  1.033928e+09
10                                           Zootopia    8.0  1.024121e+09
11                                    The Dark Knight    9.0  1.005974e+09
12              The Lord of the Rings: The Two Towers    8.7  9.474951e+08
13                                       Finding Nemo    8.1  9.403526e+08
14  The Lord of the Rings: The Fellowship of the Ring    8.8  8.976901e+08
15                                         Inside Out    8.1  8.588480e+08
16                                          Inception    8.8  8.368370e+08
17                                               Coco    8.4  8.078179e+08
18                                           Deadpool    8.0  7.828368e+08
19                            Guardians of the Galaxy    8.0  7.733501e+08

## HIGHEST REVENUE MOVIES WITH THE MOST VOTES

In [13]:
# HIGHEST REVENUE MOVIES WITH THE MOST VOTES

query = """
SELECT
    name,
    votes,
    gross
FROM movies
ORDER BY votes DESC, gross DESC
LIMIT 20;
"""

popular_movies = pd.read_sql(query, connection)

popular_movies

                                                 name      votes         gross
0                                     The Dark Knight  2400000.0  1.005974e+09
1                            The Shawshank Redemption  2400000.0  2.881729e+07
2                                           Inception  2100000.0  8.368370e+08
3                                        Forrest Gump  1900000.0  6.782261e+08
4                                        Pulp Fiction  1900000.0  2.139288e+08
5                                          Fight Club  1900000.0  1.012097e+08
6       The Lord of the Rings: The Return of the King  1700000.0  1.146031e+09
7   The Lord of the Rings: The Fellowship of the Ring  1700000.0  8.976901e+08
8                                          The Matrix  1700000.0  4.663648e+08
9                               The Dark Knight Rises  1600000.0  1.081143e+09
10                                       Interstellar  1600000.0  7.017292e+08
11              The Lord of the Rings: The Two Towers  1500000.0  9.474951e+08
12                                              Se7en  1500000.0  3.273336e+08
13                                          Gladiator  1400000.0  4.653808e+08
14                                   Django Unchained  1400000.0  4.260744e+08
15                                       The Avengers  1300000.0  1.518816e+09
16                                Saving Private Ryan  1300000.0  4.823496e+08
17                                      Batman Begins  1300000.0  3.736619e+08
18                               Inglourious Basterds  1300000.0  3.214577e+08
19                           The Silence of the Lambs  1300000.0  2.727429e+08

In [14]:
connection.close()

print("Database connection closed.")

Database connection closed.

# Summary

The SQL analysis suggests that audience popularity is associated with box office performance. Movies receiving higher IMDb ratings and larger numbers of audience votes frequently generate substantial box office revenue, although exceptions exist. Audience engagement appears to be an important contributor to commercial success, but it is unlikely to act independently of other factors such as production budget, genre, release timing, and marketing. These findings reinforce the importance of popularity as one of several factors influencing financial performance in the movie industry.