# TIME TRENDS
The objective of this notebook is to examine how box office revenue has changed over time by analysing yearly and decade-based trends. Understanding these trends provides insight into the long-term growth of the movie industry and identifies periods of exceptional commercial performance.

# Research Question

How has movie revenue changed over time?

In [5]:
import sqlite3
import pandas as pd

In [6]:
database = r"C:\Users\bongo\OneDrive\Desktop\GitHub\Movie Analysis\Database\movie_industry.db"

connection = sqlite3.connect(database)

print("Connected successfully.")

Connected successfully.

## REVENUE BY YEAR

In [7]:
# REVENUE BY YEAR

query = """
SELECT
    year,
    ROUND(SUM(gross), 2) AS Total_Revenue
FROM movies
GROUP BY year
ORDER BY year;
"""

revenue_year = pd.read_sql(query, connection)

revenue_year

    year  Total_Revenue
0   1980   2.483667e+09
1   1981   2.520065e+09
2   1982   3.187581e+09
3   1983   2.750005e+09
4   1984   3.533092e+09
5   1985   3.691509e+09
6   1986   3.647512e+09
7   1987   4.033434e+09
8   1988   4.840386e+09
9   1989   6.087251e+09
10  1990   6.804236e+09
11  1991   6.254771e+09
12  1992   7.334168e+09
13  1993   8.053959e+09
14  1994   9.062926e+09
15  1995   9.448305e+09
16  1996   9.819528e+09
17  1997   1.311228e+10
18  1998   1.117602e+10
19  1999   1.350964e+10
20  2000   1.345413e+10
21  2001   1.561763e+10
22  2002   1.700344e+10
23  2003   1.766193e+10
24  2004   1.872175e+10
25  2005   1.786661e+10
26  2006   1.865407e+10
27  2007   2.038367e+10
28  2008   2.170216e+10
29  2009   2.333868e+10
30  2010   2.310660e+10
31  2011   2.483769e+10
32  2012   2.547619e+10
33  2013   2.599585e+10
34  2014   2.649148e+10
35  2015   2.674601e+10
36  2016   2.893884e+10
37  2017   2.848525e+10
38  2018   2.808529e+10
39  2019   3.033965e+10
40  2020   2.848299e+09

## REVENUE BY DECADE

In [8]:
# REVENUE BY DECADE

query = """
SELECT
    year,
    ROUND(SUM(gross), 2) AS Total_Revenue
FROM movies
GROUP BY year
ORDER BY year;
"""

revenue_year = pd.read_sql(query, connection)

revenue_year

    year  Total_Revenue
0   1980   2.483667e+09
1   1981   2.520065e+09
2   1982   3.187581e+09
3   1983   2.750005e+09
4   1984   3.533092e+09
5   1985   3.691509e+09
6   1986   3.647512e+09
7   1987   4.033434e+09
8   1988   4.840386e+09
9   1989   6.087251e+09
10  1990   6.804236e+09
11  1991   6.254771e+09
12  1992   7.334168e+09
13  1993   8.053959e+09
14  1994   9.062926e+09
15  1995   9.448305e+09
16  1996   9.819528e+09
17  1997   1.311228e+10
18  1998   1.117602e+10
19  1999   1.350964e+10
20  2000   1.345413e+10
21  2001   1.561763e+10
22  2002   1.700344e+10
23  2003   1.766193e+10
24  2004   1.872175e+10
25  2005   1.786661e+10
26  2006   1.865407e+10
27  2007   2.038367e+10
28  2008   2.170216e+10
29  2009   2.333868e+10
30  2010   2.310660e+10
31  2011   2.483769e+10
32  2012   2.547619e+10
33  2013   2.599585e+10
34  2014   2.649148e+10
35  2015   2.674601e+10
36  2016   2.893884e+10
37  2017   2.848525e+10
38  2018   2.808529e+10
39  2019   3.033965e+10
40  2020   2.848299e+09

# Summary

The analysis demonstrates that movie revenue has changed considerably over time. While overall box office revenue generally increases across decades, changes in movie production volume and average revenue per movie suggest that industry growth is influenced by multiple factors. Examining yearly and decade-based trends provides valuable context for understanding how the movie industry has evolved and highlights periods of exceptional commercial performance.