# DATABASE EXPLORATION       
The objective of this notebook is to perform an initial exploration of the SQLite database before conducting detailed analysis. This includdes examining the size of the dataset, determining the period by the data, and calculating key descriptive statistics such as average production budget and average box office revenue. 
Understanding these qualities provides context for the analyses performed in the subsequent notebooks.

In [9]:
import sqlite3
import pandas as pd

In [10]:
database = r"C:\Users\bongo\OneDrive\Desktop\GitHub\Movie Analysis\Database\movie_industry.db"

connection = sqlite3.connect(database)

print("Connected successfully.")

Connected successfully.

### COUNT THE MOVIES

In [11]:
# COUNT THE MOVIES

query = """
SELECT COUNT(*) AS Total_Movies
FROM movies;
"""

pd.read_sql(query, connection)

   Total_Movies
0          7668

### DETERMINE THE YEAR RANGE

In [12]:
# DETERMINE THE YEAR RANGE

query = """
SELECT
    MIN(year) AS First_Year,
    MAX(year) AS Last_Year
FROM movies;
"""

pd.read_sql(query, connection)

   First_Year  Last_Year
0        1980       2020

### AVERAGE BUDGET

In [13]:
# AVERAGE BUDGET

query = """
SELECT
    ROUND(AVG(budget), 2) AS Average_Budget
FROM movies;
"""

pd.read_sql(query, connection)

   Average_Budget
0     35589876.19

### AVERAGE REVENUE

In [14]:
# AVERAGE REVENUE

query = """
SELECT
    ROUND(AVG(gross),2) AS Average_Revenue
FROM movies;
"""

pd.read_sql(query, connection)

   Average_Revenue
0      78500541.02

### SUMMARY STATISTICS

In [15]:
# SUMMARY STATISTICS

query = """
SELECT
    COUNT(*) AS Total_Movies,
    ROUND(AVG(budget),2) AS Average_Budget,
    ROUND(AVG(gross),2) AS Average_Revenue,
    MIN(year) AS First_Year,
    MAX(year) AS Last_Year
FROM movies;
"""

summary = pd.read_sql(query, connection)

summary

   Total_Movies  Average_Budget  Average_Revenue  First_Year  Last_Year
0          7668     35589876.19      78500541.02        1980       2020

In [16]:
connection.close()

print("Database connection closed.")

Database connection closed.

# Summary

The database exploration confirms that the SQLite database has been created successfully and contains all cleaned movie records. The dataset covers several decades and provides sufficient observations to investigate the factors associated with box office success. These findings establish confidence in the database before proceeding to the project's research questions.