### DATABASE EXPLORATION       
The objective of this notebook is to perform an initial exploration of the SQLite database before conducting detailed analysis. This includdes examining the size of the dataset, determining the period by the data, and calculating key descriptive statistics such as average production budget and average box office revenue. 
Understanding these qualities provides context for the analyses performed in the subsequent notebooks.

In [1]:
import sqlite3
import pandas as pd

In [3]:
database = r"C:\Users\bongo\OneDrive\Desktop\GitHub\Movie Analysis\Database\movie_industry.db"

connection = sqlite3.connect(database)

print("Connected successfully.")

Connected successfully.

In [4]:
query = """
SELECT COUNT(*) AS Total_Movies
FROM movies;
"""

pd.read_sql(query, connection)

   Total_Movies
0          7668

In [5]:
query = """
SELECT
    MIN(year) AS First_Year,
    MAX(year) AS Last_Year
FROM movies;
"""

pd.read_sql(query, connection)

   First_Year  Last_Year
0        1980       2020

In [6]:
query = """
SELECT
    ROUND(AVG(budget), 2) AS Average_Budget
FROM movies;
"""

pd.read_sql(query, connection)

   Average_Budget
0     35589876.19

In [7]:
query = """
SELECT
    ROUND(AVG(gross),2) AS Average_Revenue
FROM movies;
"""

pd.read_sql(query, connection)

   Average_Revenue
0      78500541.02

In [8]:
query = """
SELECT
    COUNT(*) AS Total_Movies,
    ROUND(AVG(budget),2) AS Average_Budget,
    ROUND(AVG(gross),2) AS Average_Revenue,
    MIN(year) AS First_Year,
    MAX(year) AS Last_Year
FROM movies;
"""

summary = pd.read_sql(query, connection)

summary

   Total_Movies  Average_Budget  Average_Revenue  First_Year  Last_Year
0          7668     35589876.19      78500541.02        1980       2020

In [9]:
connection.close()

print("Database connection closed.")

Database connection closed.